package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BlockedProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedProfileAllPropertiesEquals(BlockedProfile expected, BlockedProfile actual) {
        assertBlockedProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertBlockedProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedProfileAllUpdatablePropertiesEquals(BlockedProfile expected, BlockedProfile actual) {
        assertBlockedProfileUpdatableFieldsEquals(expected, actual);
        assertBlockedProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedProfileAutoGeneratedPropertiesEquals(BlockedProfile expected, BlockedProfile actual) {
        assertThat(actual)
            .as("Verify BlockedProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedProfileUpdatableFieldsEquals(BlockedProfile expected, BlockedProfile actual) {
        assertThat(actual)
            .as("Verify BlockedProfile relevant properties")
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getDateBlocked()).as("check dateBlocked").isEqualTo(expected.getDateBlocked()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlockedProfileUpdatableRelationshipsEquals(BlockedProfile expected, BlockedProfile actual) {
        assertThat(actual)
            .as("Verify BlockedProfile relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getBlockedProfile()).as("check blockedProfile").isEqualTo(expected.getBlockedProfile()));
    }
}
