package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FollowingProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowingProfileAllPropertiesEquals(FollowingProfile expected, FollowingProfile actual) {
        assertFollowingProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertFollowingProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowingProfileAllUpdatablePropertiesEquals(FollowingProfile expected, FollowingProfile actual) {
        assertFollowingProfileUpdatableFieldsEquals(expected, actual);
        assertFollowingProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowingProfileAutoGeneratedPropertiesEquals(FollowingProfile expected, FollowingProfile actual) {
        assertThat(actual)
            .as("Verify FollowingProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowingProfileUpdatableFieldsEquals(FollowingProfile expected, FollowingProfile actual) {
        assertThat(actual)
            .as("Verify FollowingProfile relevant properties")
            .satisfies(a -> assertThat(a.getDateFollowing()).as("check dateFollowing").isEqualTo(expected.getDateFollowing()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFollowingProfileUpdatableRelationshipsEquals(FollowingProfile expected, FollowingProfile actual) {
        assertThat(actual)
            .as("Verify FollowingProfile relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getFollowedProfile()).as("check followedProfile").isEqualTo(expected.getFollowedProfile()));
    }
}
