package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaSetTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetTypeAllPropertiesEquals(MegaSetType expected, MegaSetType actual) {
        assertMegaSetTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaSetTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetTypeAllUpdatablePropertiesEquals(MegaSetType expected, MegaSetType actual) {
        assertMegaSetTypeUpdatableFieldsEquals(expected, actual);
        assertMegaSetTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetTypeAutoGeneratedPropertiesEquals(MegaSetType expected, MegaSetType actual) {
        assertThat(actual)
            .as("Verify MegaSetType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetTypeUpdatableFieldsEquals(MegaSetType expected, MegaSetType actual) {
        assertThat(actual)
            .as("Verify MegaSetType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getIsLatest()).as("check isLatest").isEqualTo(expected.getIsLatest()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetTypeUpdatableRelationshipsEquals(MegaSetType expected, MegaSetType actual) {
        assertThat(actual)
            .as("Verify MegaSetType relationships")
            .satisfies(a -> assertThat(a.getAttributes()).as("check attributes").isEqualTo(expected.getAttributes()));
    }
}
