package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaAttributeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeAllPropertiesEquals(MegaAttribute expected, MegaAttribute actual) {
        assertMegaAttributeAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaAttributeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeAllUpdatablePropertiesEquals(MegaAttribute expected, MegaAttribute actual) {
        assertMegaAttributeUpdatableFieldsEquals(expected, actual);
        assertMegaAttributeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeAutoGeneratedPropertiesEquals(MegaAttribute expected, MegaAttribute actual) {
        assertThat(actual)
            .as("Verify MegaAttribute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeUpdatableFieldsEquals(MegaAttribute expected, MegaAttribute actual) {
        assertThat(actual)
            .as("Verify MegaAttribute relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getUiComponent()).as("check uiComponent").isEqualTo(expected.getUiComponent()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getRequired()).as("check required").isEqualTo(expected.getRequired()))
            .satisfies(a -> assertThat(a.getMultiple()).as("check multiple").isEqualTo(expected.getMultiple()))
            .satisfies(a -> assertThat(a.getDefaultValue()).as("check defaultValue").isEqualTo(expected.getDefaultValue()))
            .satisfies(a -> assertThat(a.getMinNumber()).as("check minNumber").isEqualTo(expected.getMinNumber()))
            .satisfies(a -> assertThat(a.getMaxNumber()).as("check maxNumber").isEqualTo(expected.getMaxNumber()))
            .satisfies(a -> assertThat(a.getMinLength()).as("check minLength").isEqualTo(expected.getMinLength()))
            .satisfies(a -> assertThat(a.getMaxLength()).as("check maxLength").isEqualTo(expected.getMaxLength()))
            .satisfies(a -> assertThat(a.getRegex()).as("check regex").isEqualTo(expected.getRegex()))
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()))
            .satisfies(a -> assertThat(a.getAttributeGroup()).as("check attributeGroup").isEqualTo(expected.getAttributeGroup()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeUpdatableRelationshipsEquals(MegaAttribute expected, MegaAttribute actual) {
        assertThat(actual)
            .as("Verify MegaAttribute relationships")
            .satisfies(a -> assertThat(a.getSetTypes()).as("check setTypes").isEqualTo(expected.getSetTypes()))
            .satisfies(a -> assertThat(a.getPartTypes()).as("check partTypes").isEqualTo(expected.getPartTypes()));
    }
}
