package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetAllPropertiesEquals(MegaSet expected, MegaSet actual) {
        assertMegaSetAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetAllUpdatablePropertiesEquals(MegaSet expected, MegaSet actual) {
        assertMegaSetUpdatableFieldsEquals(expected, actual);
        assertMegaSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetAutoGeneratedPropertiesEquals(MegaSet expected, MegaSet actual) {
        assertThat(actual)
            .as("Verify MegaSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetUpdatableFieldsEquals(MegaSet expected, MegaSet actual) {
        assertThat(actual)
            .as("Verify MegaSet relevant properties")
            .satisfies(a -> assertThat(a.getSetNumber()).as("check setNumber").isEqualTo(expected.getSetNumber()))
            .satisfies(a -> assertThat(a.getReleaseDate()).as("check releaseDate").isEqualTo(expected.getReleaseDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getAttributes()).as("check attributes").isEqualTo(expected.getAttributes()))
            .satisfies(a ->
                assertThat(a.getAttributesContentType()).as("check attributes content type").isEqualTo(expected.getAttributesContentType())
            )
            .satisfies(a ->
                assertThat(a.getOwner() == null ? null : a.getOwner().getId())
                    .as("check owner id")
                    .isEqualTo(expected.getOwner() == null ? null : expected.getOwner().getId())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetUpdatableRelationshipsEquals(MegaSet expected, MegaSet actual) {
        assertThat(actual)
            .as("Verify MegaSet relationships")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()));
    }
}
