package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaAssetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAssetAllPropertiesEquals(MegaAsset expected, MegaAsset actual) {
        assertMegaAssetAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaAssetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAssetAllUpdatablePropertiesEquals(MegaAsset expected, MegaAsset actual) {
        assertMegaAssetUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAssetAutoGeneratedPropertiesEquals(MegaAsset expected, MegaAsset actual) {
        assertThat(actual)
            .as("Verify MegaAsset auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAssetUpdatableFieldsEquals(MegaAsset expected, MegaAsset actual) {
        assertThat(actual)
            .as("Verify MegaAsset relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()))
            .satisfies(a -> assertThat(a.getExtension()).as("check extension").isEqualTo(expected.getExtension()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getContentType()).as("check contentType").isEqualTo(expected.getContentType()))
            .satisfies(a -> assertThat(a.getSizeBytes()).as("check sizeBytes").isEqualTo(expected.getSizeBytes()))
            .satisfies(a -> assertThat(a.isPublic()).as("check isPublic").isEqualTo(expected.isPublic()))
            .satisfies(a ->
                assertThat(a.getOwner() == null ? null : a.getOwner().getId())
                    .as("check owner id")
                    .isEqualTo(expected.getOwner() == null ? null : expected.getOwner().getId())
            );
    }
}
