package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetAllPropertiesEquals(MegaSet expected, MegaSet actual) {
        assertMegaSetAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetAllUpdatablePropertiesEquals(MegaSet expected, MegaSet actual) {
        assertMegaSetUpdatableFieldsEquals(expected, actual);
        assertMegaSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetAutoGeneratedPropertiesEquals(MegaSet expected, MegaSet actual) {
        assertThat(actual)
            .as("Verify MegaSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetUpdatableFieldsEquals(MegaSet expected, MegaSet actual) {
        assertThat(actual)
            .as("Verify MegaSet relevant properties")
            .satisfies(a -> assertThat(a.getSetNumber()).as("check setNumber").isEqualTo(expected.getSetNumber()))
            .satisfies(a -> assertThat(a.getReleaseDate()).as("check releaseDate").isEqualTo(expected.getReleaseDate()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getNameEN()).as("check nameEN").isEqualTo(expected.getNameEN()))
            .satisfies(a -> assertThat(a.getNameES()).as("check nameES").isEqualTo(expected.getNameES()))
            .satisfies(a -> assertThat(a.getNameDE()).as("check nameDE").isEqualTo(expected.getNameDE()))
            .satisfies(a -> assertThat(a.getNameFR()).as("check nameFR").isEqualTo(expected.getNameFR()))
            .satisfies(a -> assertThat(a.getDescriptionEN()).as("check descriptionEN").isEqualTo(expected.getDescriptionEN()))
            .satisfies(a -> assertThat(a.getDescriptionES()).as("check descriptionES").isEqualTo(expected.getDescriptionES()))
            .satisfies(a -> assertThat(a.getDescriptionDE()).as("check descriptionDE").isEqualTo(expected.getDescriptionDE()))
            .satisfies(a -> assertThat(a.getDescriptionFR()).as("check descriptionFR").isEqualTo(expected.getDescriptionFR()))
            .satisfies(a -> assertThat(a.getAttributes()).as("check attributes").isEqualTo(expected.getAttributes()))
            .satisfies(a ->
                assertThat(a.getAttributesContentType()).as("check attributes content type").isEqualTo(expected.getAttributesContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetUpdatableRelationshipsEquals(MegaSet expected, MegaSet actual) {
        assertThat(actual)
            .as("Verify MegaSet relationships")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a ->
                assertThat(a.getProfileCollectionSets()).as("check profileCollectionSets").isEqualTo(expected.getProfileCollectionSets())
            );
    }
}
