package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaAttributeOptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeOptionAllPropertiesEquals(MegaAttributeOption expected, MegaAttributeOption actual) {
        assertMegaAttributeOptionAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaAttributeOptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeOptionAllUpdatablePropertiesEquals(MegaAttributeOption expected, MegaAttributeOption actual) {
        assertMegaAttributeOptionUpdatableFieldsEquals(expected, actual);
        assertMegaAttributeOptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeOptionAutoGeneratedPropertiesEquals(MegaAttributeOption expected, MegaAttributeOption actual) {
        assertThat(actual)
            .as("Verify MegaAttributeOption auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeOptionUpdatableFieldsEquals(MegaAttributeOption expected, MegaAttributeOption actual) {
        assertThat(actual)
            .as("Verify MegaAttributeOption relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaAttributeOptionUpdatableRelationshipsEquals(MegaAttributeOption expected, MegaAttributeOption actual) {
        assertThat(actual)
            .as("Verify MegaAttributeOption relationships")
            .satisfies(a -> assertThat(a.getAttribute()).as("check attribute").isEqualTo(expected.getAttribute()));
    }
}
