package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartCategoryAllPropertiesEquals(PartCategory expected, PartCategory actual) {
        assertPartCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertPartCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartCategoryAllUpdatablePropertiesEquals(PartCategory expected, PartCategory actual) {
        assertPartCategoryUpdatableFieldsEquals(expected, actual);
        assertPartCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartCategoryAutoGeneratedPropertiesEquals(PartCategory expected, PartCategory actual) {
        assertThat(actual)
            .as("Verify PartCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartCategoryUpdatableFieldsEquals(PartCategory expected, PartCategory actual) {
        assertThat(actual)
            .as("Verify PartCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartCategoryUpdatableRelationshipsEquals(PartCategory expected, PartCategory actual) {
        // empty method
    }
}
