package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileRequestTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestTypeAllPropertiesEquals(ProfileRequestType expected, ProfileRequestType actual) {
        assertProfileRequestTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileRequestTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestTypeAllUpdatablePropertiesEquals(ProfileRequestType expected, ProfileRequestType actual) {
        assertProfileRequestTypeUpdatableFieldsEquals(expected, actual);
        assertProfileRequestTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestTypeAutoGeneratedPropertiesEquals(ProfileRequestType expected, ProfileRequestType actual) {
        assertThat(actual)
            .as("Verify ProfileRequestType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestTypeUpdatableFieldsEquals(ProfileRequestType expected, ProfileRequestType actual) {
        assertThat(actual)
            .as("Verify ProfileRequestType relevant properties")
            .satisfies(a -> assertThat(a.getKey()).as("check key").isEqualTo(expected.getKey()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestTypeUpdatableRelationshipsEquals(ProfileRequestType expected, ProfileRequestType actual) {
        // empty method
    }
}
