package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileCollectionSetAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionSetAllPropertiesEquals(ProfileCollectionSet expected, ProfileCollectionSet actual) {
        assertProfileCollectionSetAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileCollectionSetAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionSetAllUpdatablePropertiesEquals(ProfileCollectionSet expected, ProfileCollectionSet actual) {
        assertProfileCollectionSetUpdatableFieldsEquals(expected, actual);
        assertProfileCollectionSetUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionSetAutoGeneratedPropertiesEquals(ProfileCollectionSet expected, ProfileCollectionSet actual) {
        assertThat(actual)
            .as("Verify ProfileCollectionSet auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionSetUpdatableFieldsEquals(ProfileCollectionSet expected, ProfileCollectionSet actual) {
        assertThat(actual)
            .as("Verify ProfileCollectionSet relevant properties")
            .satisfies(a -> assertThat(a.getOwned()).as("check owned").isEqualTo(expected.getOwned()))
            .satisfies(a -> assertThat(a.getWanted()).as("check wanted").isEqualTo(expected.getWanted()))
            .satisfies(a -> assertThat(a.getDateAdded()).as("check dateAdded").isEqualTo(expected.getDateAdded()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileCollectionSetUpdatableRelationshipsEquals(ProfileCollectionSet expected, ProfileCollectionSet actual) {
        assertThat(actual)
            .as("Verify ProfileCollectionSet relationships")
            .satisfies(a -> assertThat(a.getCollection()).as("check collection").isEqualTo(expected.getCollection()))
            .satisfies(a -> assertThat(a.getSets()).as("check sets").isEqualTo(expected.getSets()));
    }
}
