package com.nookx.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestAllPropertiesEquals(ProfileRequest expected, ProfileRequest actual) {
        assertProfileRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestAllUpdatablePropertiesEquals(ProfileRequest expected, ProfileRequest actual) {
        assertProfileRequestUpdatableFieldsEquals(expected, actual);
        assertProfileRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestAutoGeneratedPropertiesEquals(ProfileRequest expected, ProfileRequest actual) {
        assertThat(actual)
            .as("Verify ProfileRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestUpdatableFieldsEquals(ProfileRequest expected, ProfileRequest actual) {
        assertThat(actual)
            .as("Verify ProfileRequest relevant properties")
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileRequestUpdatableRelationshipsEquals(ProfileRequest expected, ProfileRequest actual) {
        assertThat(actual)
            .as("Verify ProfileRequest relationships")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()));
    }
}
