package com.dot.collector.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaPartTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartTypeAllPropertiesEquals(MegaPartType expected, MegaPartType actual) {
        assertMegaPartTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaPartTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartTypeAllUpdatablePropertiesEquals(MegaPartType expected, MegaPartType actual) {
        assertMegaPartTypeUpdatableFieldsEquals(expected, actual);
        assertMegaPartTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartTypeAutoGeneratedPropertiesEquals(MegaPartType expected, MegaPartType actual) {
        assertThat(actual)
            .as("Verify MegaPartType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartTypeUpdatableFieldsEquals(MegaPartType expected, MegaPartType actual) {
        assertThat(actual)
            .as("Verify MegaPartType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getIsLatest()).as("check isLatest").isEqualTo(expected.getIsLatest()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartTypeUpdatableRelationshipsEquals(MegaPartType expected, MegaPartType actual) {
        assertThat(actual)
            .as("Verify MegaPartType relationships")
            .satisfies(a -> assertThat(a.getAttributes()).as("check attributes").isEqualTo(expected.getAttributes()));
    }
}
