package com.dot.collector.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaPartSubPartCountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartSubPartCountAllPropertiesEquals(MegaPartSubPartCount expected, MegaPartSubPartCount actual) {
        assertMegaPartSubPartCountAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaPartSubPartCountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartSubPartCountAllUpdatablePropertiesEquals(MegaPartSubPartCount expected, MegaPartSubPartCount actual) {
        assertMegaPartSubPartCountUpdatableFieldsEquals(expected, actual);
        assertMegaPartSubPartCountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartSubPartCountAutoGeneratedPropertiesEquals(MegaPartSubPartCount expected, MegaPartSubPartCount actual) {
        assertThat(actual)
            .as("Verify MegaPartSubPartCount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartSubPartCountUpdatableFieldsEquals(MegaPartSubPartCount expected, MegaPartSubPartCount actual) {
        assertThat(actual)
            .as("Verify MegaPartSubPartCount relevant properties")
            .satisfies(a -> assertThat(a.getCount()).as("check count").isEqualTo(expected.getCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartSubPartCountUpdatableRelationshipsEquals(MegaPartSubPartCount expected, MegaPartSubPartCount actual) {
        assertThat(actual)
            .as("Verify MegaPartSubPartCount relationships")
            .satisfies(a -> assertThat(a.getPart()).as("check part").isEqualTo(expected.getPart()))
            .satisfies(a -> assertThat(a.getParentPart()).as("check parentPart").isEqualTo(expected.getParentPart()));
    }
}
