package com.dot.collector.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaPartAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartAllPropertiesEquals(MegaPart expected, MegaPart actual) {
        assertMegaPartAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaPartAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartAllUpdatablePropertiesEquals(MegaPart expected, MegaPart actual) {
        assertMegaPartUpdatableFieldsEquals(expected, actual);
        assertMegaPartUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartAutoGeneratedPropertiesEquals(MegaPart expected, MegaPart actual) {
        assertThat(actual)
            .as("Verify MegaPart auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartUpdatableFieldsEquals(MegaPart expected, MegaPart actual) {
        assertThat(actual)
            .as("Verify MegaPart relevant properties")
            .satisfies(a -> assertThat(a.getReleaseDate()).as("check releaseDate").isEqualTo(expected.getReleaseDate()))
            .satisfies(a -> assertThat(a.getPartNumber()).as("check partNumber").isEqualTo(expected.getPartNumber()))
            .satisfies(a -> assertThat(a.getNameEN()).as("check nameEN").isEqualTo(expected.getNameEN()))
            .satisfies(a -> assertThat(a.getNameES()).as("check nameES").isEqualTo(expected.getNameES()))
            .satisfies(a -> assertThat(a.getNameDE()).as("check nameDE").isEqualTo(expected.getNameDE()))
            .satisfies(a -> assertThat(a.getNameFR()).as("check nameFR").isEqualTo(expected.getNameFR()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getAttributes()).as("check attributes").isEqualTo(expected.getAttributes()))
            .satisfies(a ->
                assertThat(a.getAttributesContentType()).as("check attributes content type").isEqualTo(expected.getAttributesContentType())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaPartUpdatableRelationshipsEquals(MegaPart expected, MegaPart actual) {
        assertThat(actual)
            .as("Verify MegaPart relationships")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getPartCategory()).as("check partCategory").isEqualTo(expected.getPartCategory()))
            .satisfies(a -> assertThat(a.getPartSubCategories()).as("check partSubCategories").isEqualTo(expected.getPartSubCategories()));
    }
}
