package com.dot.collector.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MegaSetPartCountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetPartCountAllPropertiesEquals(MegaSetPartCount expected, MegaSetPartCount actual) {
        assertMegaSetPartCountAutoGeneratedPropertiesEquals(expected, actual);
        assertMegaSetPartCountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetPartCountAllUpdatablePropertiesEquals(MegaSetPartCount expected, MegaSetPartCount actual) {
        assertMegaSetPartCountUpdatableFieldsEquals(expected, actual);
        assertMegaSetPartCountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetPartCountAutoGeneratedPropertiesEquals(MegaSetPartCount expected, MegaSetPartCount actual) {
        assertThat(actual)
            .as("Verify MegaSetPartCount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetPartCountUpdatableFieldsEquals(MegaSetPartCount expected, MegaSetPartCount actual) {
        assertThat(actual)
            .as("Verify MegaSetPartCount relevant properties")
            .satisfies(a -> assertThat(a.getCount()).as("check count").isEqualTo(expected.getCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMegaSetPartCountUpdatableRelationshipsEquals(MegaSetPartCount expected, MegaSetPartCount actual) {
        assertThat(actual)
            .as("Verify MegaSetPartCount relationships")
            .satisfies(a -> assertThat(a.getSet()).as("check set").isEqualTo(expected.getSet()))
            .satisfies(a -> assertThat(a.getPart()).as("check part").isEqualTo(expected.getPart()));
    }
}
