package com.dot.collector.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PartSubCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartSubCategoryAllPropertiesEquals(PartSubCategory expected, PartSubCategory actual) {
        assertPartSubCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertPartSubCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartSubCategoryAllUpdatablePropertiesEquals(PartSubCategory expected, PartSubCategory actual) {
        assertPartSubCategoryUpdatableFieldsEquals(expected, actual);
        assertPartSubCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartSubCategoryAutoGeneratedPropertiesEquals(PartSubCategory expected, PartSubCategory actual) {
        assertThat(actual)
            .as("Verify PartSubCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartSubCategoryUpdatableFieldsEquals(PartSubCategory expected, PartSubCategory actual) {
        assertThat(actual)
            .as("Verify PartSubCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPartSubCategoryUpdatableRelationshipsEquals(PartSubCategory expected, PartSubCategory actual) {
        assertThat(actual)
            .as("Verify PartSubCategory relationships")
            .satisfies(a -> assertThat(a.getMegaParts()).as("check megaParts").isEqualTo(expected.getMegaParts()));
    }
}
